# Generated by Django 4.0 on 2021-12-08 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlleyLane',
            fields=[
                ('AlleyLaneID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=64, unique=True)),
                ('FirstName', models.CharField(max_length=64)),
                ('LastName', models.CharField(max_length=64)),
                ('PhoneNumber', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=128)),
                ('Password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('PlayerID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=64)),
                ('LastName', models.CharField(max_length=64)),
                ('ShoeSize', models.IntegerField()),
                ('BallSize', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('BookingsID', models.AutoField(primary_key=True, serialize=False)),
                ('NumberOfPlayers', models.IntegerField()),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Status', models.CharField(max_length=32)),
                ('AlleyLaneID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.alleylane')),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.customer')),
                ('PlayerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.player')),
            ],
        ),
    ]
