# Generated by Django 4.0 on 2021-12-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alleylane',
            name='Status',
            field=models.CharField(default='closed', max_length=32),
        ),
    ]
