# Generated by Django 4.0 on 2021-12-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='EmailAddress',
            field=models.EmailField(max_length=128),
        ),
        migrations.AlterField(
            model_name='account',
            name='FirstName',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='account',
            name='LastName',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='account',
            name='Password',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='account',
            name='PhoneNumber',
            field=models.CharField(max_length=10),
        ),
    ]
