# Generated by Django 4.0 on 2021-12-23 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_rename_userid_account_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='UserId',
            new_name='UserID',
        ),
    ]
