# Generated by Django 4.0 on 2021-12-13 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlleyLane',
            fields=[
                ('AlleyLaneID', models.AutoField(primary_key=True, serialize=False)),
                ('Available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('PlayerID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('BookingID', models.AutoField(primary_key=True, serialize=False)),
                ('NumberOfPlayers', models.IntegerField()),
                ('DateTime', models.DateTimeField()),
                ('AlleyLaneID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookings.alleylane')),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.account')),
                ('Players', models.ManyToManyField(to='Bookings.Player')),
            ],
        ),
    ]
