# Generated by Django 3.2.9 on 2021-12-22 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingmodel',
            old_name='CustomerId',
            new_name='Customer',
        ),
    ]
