# Generated by Django 4.0 on 2021-12-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('PlayerID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='Players',
            field=models.ManyToManyField(to='Bookings.Player'),
        ),
    ]
